version: 2.0.3.{build}
image: Visual Studio 2015
before_build:
- dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
after_build:
- ps: .\pack.ps1
artifacts:
- path: NuGet\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: iB6H1i7PekG+Ls4pbFnd7yyDeJP9IjaD7zWhxFlbflpKkfpDq+lU7vKURO8K9NJ4
  artifact: NuGet
test: off

